-- Migration: create reviews table
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id integer not null,
  user_id uuid,
  author_name text,
  rating smallint not null check (rating >= 1 and rating <= 5),
  content text not null,
  created_at timestamptz default now()
);

create index if not exists idx_reviews_product_id on public.reviews (product_id);
